server:
  port: 8082

spring:
  application:
    name: InventoryService
  datasource:
    url: ${INVENTORY_DB_URI}
    username: ${INVENTORY_DB_USER}
    password: ${INVENTORY_DB_PASSWORD}
    driver-class-name: ${INVENTORY_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${INVENTORY_DB_DIALECT}
  cloud:
    vault:
      uri: ${VAULT_SERVER_HOST}
      token: ${VAULT_TOKEN}
      authentication: token
      scheme: http
      kv:
        enabled: true
        backend: secrets
        default-context: inventory
        profile-separator: "/"
  config:
    import: vault://
    
springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always

